In [21]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output, State

In [22]:
file_path = 'data/olympics.csv'
olympics_df_uncleaned = pd.read_csv(file_path)
print(olympics_df_uncleaned.head())
olympics_df_uncleaned.shape

   id                      name sex   age  height  weight            team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China
1   2                  A Lamusi   M  23.0   170.0    60.0           China
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands

   noc        games  year  season       city          sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball
1  CHN  2012 Summer  2012  Summer     London           Judo
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating

                              event medal
0       Basketball Men's Basketball   NaN
1      Judo Men's Extra-Lightweight   NaN
2           Football Men's Football   NaN
3       Tug-Of-War Men's Tug-Of-War  Gold
4  Speed Skating Women's 500 metres   NaN

(271116, 15)

In [23]:
#cleaning steps
df_olympics_cleaning = olympics_df_uncleaned.dropna(subset=['medal'])
df_olympics_cleaning

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver

In [24]:
# Define a mapping of Olympic host cities to their respective countries
city_to_country = {
    "Albertville": "France",
    "Amsterdam": "Netherlands",
    "Antwerp": "Belgium",
    "Antwerpen": "Belgium",  # Alternative spelling
    "Athens": "Greece",
    "Athina": "Greece",  # Alternative spelling
    "Atlanta": "USA",
    "Barcelona": "Spain",
    "Beijing": "China",
    "Berlin": "Germany",
    "Calgary": "Canada",
    "Chamonix": "France",
    "Cortina d'Ampezzo": "Italy",
    "Garmisch-Partenkirchen": "Germany",
    "Grenoble": "France",
    "Helsinki": "Finland",
    "Innsbruck": "Austria",
    "Lake Placid": "USA",
    "Lillehammer": "Norway",
    "London": "UK",
    "Los Angeles": "USA",
    "Melbourne": "Australia",
    "Mexico City": "Mexico",
    "Montreal": "Canada",
    "Moscow": "Russia",
    "Moskva": "Russia",  # Alternative spelling
    "Munich": "Germany",
    "Nagano": "Japan",
    "Oslo": "Norway",
    "Paris": "France",
    "Rio de Janeiro": "Brazil",
    "Rome": "Italy",
    "Roma": "Italy",  # Alternative spelling
    "Salt Lake City": "USA",
    "Sankt Moritz": "Switzerland",  # Alternative spelling of St. Moritz
    "Sapporo": "Japan",
    "Sarajevo": "Bosnia and Herzegovina",
    "Seoul": "South Korea",
    "Sochi": "Russia",
    "Squaw Valley": "USA",
    "St. Louis": "USA",
    "Stockholm": "Sweden",
    "Sydney": "Australia",
    "Tokyo": "Japan",
    "Torino": "Italy",
    "Vancouver": "Canada"
}


# Map the city column to the corresponding country
df_olympics_cleaning["country"] = df_olympics_cleaning["city"].map(city_to_country)

# Show the first few rows with the new country column
print(df_olympics_cleaning.head())

    id                      name sex   age  height  weight            team  \
3    4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden
37  15      Arvo Ossian Aaltonen   M  30.0     NaN     NaN         Finland
38  15      Arvo Ossian Aaltonen   M  30.0     NaN     NaN         Finland
40  16  Juhamatti Tapio Aaltonen   M  28.0   184.0    85.0         Finland
41  17   Paavo Johannes Aaltonen   M  28.0   175.0    64.0         Finland

    noc        games  year  season       city       sport  \
3   DEN  1900 Summer  1900  Summer      Paris  Tug-Of-War
37  FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
38  FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
40  FIN  2014 Winter  2014  Winter      Sochi  Ice Hockey
41  FIN  1948 Summer  1948  Summer     London  Gymnastics

                                     event   medal  country
3              Tug-Of-War Men's Tug-Of-War    Gold   France
37  Swimming Men's 200 metres Breaststroke  Bronze  Belgium
38  Swimming Men's 400 metres Breaststroke  Bronze  Belgium
40             Ice Hockey Men's Ice Hockey  Bronze   Russia
41  Gymnastics Men's Individual All-Around  Bronze       UK

C:\Users\schew\AppData\Local\Temp\ipykernel_7888\2389496699.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_olympics_cleaning["country"] = df_olympics_cleaning["city"].map(city_to_country)

In [25]:
#drop duplicates 
df_olympics_cleaning = df_olympics_cleaning.drop_duplicates()

In [26]:
# print number of duplicate rows after cleaning 
num_duplicate_rows = df_olympics_cleaning.duplicated().sum()
print("Number of duplicate rows after cleaning:", num_duplicate_rows)
# and isolate data from years 1960 to 2020 
df_olympics_cleaned_1960_2020 = df_olympics_cleaning[(df_olympics_cleaning['year'] >= 1960) & (df_olympics_cleaning['year'] <= 2020)]
df_olympics_cleaned_1960_2020

Number of duplicate rows after cleaning: 0

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal,country
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Russia
60,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Super G,Gold,France
61,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze,France
63,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Downhill,Silver,Norway
64,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Super G,Bronze,Norway
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271049,135545,Henk Jan Zwolle,M,31.0,197.0,93.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Coxed Eights,Gold,USA
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Japan
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze,Russia
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze,Australia
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver,Greece

In [27]:
#clean the team names (e.g. United States, United States-1 and United States-2) and remove data for fake teams eg Shrek 
import re

def clean_team_name(team):
    # Remove numeric suffixes like '-1', '-2', etc.
    team = re.sub(r"-\d+$", "", team)
    return team

# Apply the cleaning function
df_olympics_cleaned_1960_2020["team"] = df_olympics_cleaned_1960_2020["team"].astype(str).apply(clean_team_name)

# Remove non-country entries (manually identified)
invalid_entries = [
    "Elvis Va", "Bonaparte", "Nadine", "Sunrise", "Salinero", "Satchmo", 
    "Digby", "Clearwater", "Don Schufro", "Mutafo", "Bingo", "Widgeon", 
    "White Lady", "Gem", "Aphrodite", "Rush VII", "Lady C", "Barrenjoey", 
    "Pandora", "Humbug V", "Glider", "Sirene", "Web II", "Tango", "Venilia", 
    "Ballerina IV", "Nirefs", "Skum", "Shrew II", "Minotaur", "Macky VI", 
    "Tornado", "Ma'Lindo"
]

# Keep only valid country names
df_olympics_cleaned_1960_2020 = df_olympics_cleaned_1960_2020[~df_olympics_cleaned_1960_2020["team"].isin(invalid_entries)]

# Check cleaned country names
print(df_olympics_cleaned_1960_2020["team"].unique())

['Finland' 'Norway' 'Netherlands' 'Italy' 'Spain' 'Azerbaijan' 'Russia'
 'Belarus' 'France' 'Cameroon' 'United States' 'Hungary' 'Australia'
 'Iran' 'Canada' 'Pakistan' 'Soviet Union' 'Uzbekistan' 'Tajikistan'
 'Unified Team' 'Japan' 'Ethiopia' 'East Germany' 'Turkey' 'Bulgaria'
 'Egypt' 'Great Britain' 'Sweden' 'Jordan' 'Romania' 'Switzerland'
 'Puerto Rico' 'Mexico' 'Ghana' 'Morocco' 'New Zealand' 'Germany'
 'Argentina' 'Cuba' 'Poland' 'Czechoslovakia' 'Nigeria' 'Brazil'
 'Lithuania' 'South Africa' 'Indonesia' 'Ukraine' 'Greece' 'Uganda'
 'Syria' 'Qatar' 'Kuwait' 'Individual Olympic Athletes' 'Saudi Arabia'
 'United Arab Emirates' 'Croatia' 'West Germany' 'Armenia' 'Serbia'
 'Niger' 'India' 'Algeria' 'Austria' 'Jamaica' 'Trinidad and Tobago'
 'Chile' 'Colombia' 'Botswana' 'Tunisia' 'South Korea' 'North Korea'
 'China' 'Yugoslavia' 'Denmark' 'Guyana' 'Israel' 'Kazakhstan' 'Georgia'
 'Kenya' 'Iceland' 'Malaysia' 'Iraq' 'Czech Republic' 'Slovakia' 'Bahamas'
 'Paraguay' 'Montenegro' 'Ireland' 'Portugal' 'Guatemala'
 'Serbia and Montenegro' 'Tanzania' 'Lebanon' 'Kyrgyzstan' 'Belgium'
 'Netherlands Antilles' 'Venezuela' 'Thailand' 'Togo' 'Peru' 'Estonia'
 'Slovenia' 'Chinese Taipei' 'Zimbabwe' 'Mongolia' 'Moldova'
 "Cote d'Ivoire" 'Fiji' 'Senegal' 'Dominican Republic' 'Philippines'
 'Latvia' 'United Arab Republic' 'Singapore' 'Namibia' 'Liechtenstein'
 'West Indies Federation' 'Luxembourg' 'Bermuda' 'Vietnam'
 'United States Virgin Islands' 'Macedonia' 'Sudan' 'Bahrain' 'Grenada'
 'Sri Lanka' 'Mauritius' 'Kosovo' 'Hong Kong' 'Cyprus' 'Zambia'
 'Mozambique' 'Suriname' 'Afghanistan' 'Burundi' 'Gabon' 'Ecuador'
 'Costa Rica' 'Uruguay' 'Panama' 'Djibouti' 'Eritrea' 'Barbados' 'Tonga']

C:\Users\schew\AppData\Local\Temp\ipykernel_7888\171481496.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_olympics_cleaned_1960_2020["team"] = df_olympics_cleaned_1960_2020["team"].astype(str).apply(clean_team_name)

In [28]:
# df_olympics_cleaned_1960_2020.to_csv('data/olympics_cleaned.csv')

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal,country
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Russia
60,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Super G,Gold,France
61,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze,France
63,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Downhill,Silver,Norway
64,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Super G,Bronze,Norway
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271049,135545,Henk Jan Zwolle,M,31.0,197.0,93.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Coxed Eights,Gold,USA
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Japan
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze,Russia
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze,Australia
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver,Greece