In [143]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output, State

In [145]:
file_path = '/Users/samimorris/Desktop/UNI/SEM 8/COMP4010/Project 1/Part 1/olympics.csv'
olympics_df_uncleaned = pd.read_csv(file_path)
print(olympics_df_uncleaned.head())
olympics_df_uncleaned.shape

   id               name sex   age  height  weight     team  noc        games  \
0  22      Andreea Aanei   F  22.0   170.0   125.0  Romania  ROU  2016 Summer
1  51  Nstor Abad Sanjun   M  23.0   167.0    64.0    Spain  ESP  2016 Summer
2  51  Nstor Abad Sanjun   M  23.0   167.0    64.0    Spain  ESP  2016 Summer
3  51  Nstor Abad Sanjun   M  23.0   167.0    64.0    Spain  ESP  2016 Summer
4  51  Nstor Abad Sanjun   M  23.0   167.0    64.0    Spain  ESP  2016 Summer

   year  season            city          sport  \
0  2016  Summer  Rio de Janeiro  Weightlifting
1  2016  Summer  Rio de Janeiro     Gymnastics
2  2016  Summer  Rio de Janeiro     Gymnastics
3  2016  Summer  Rio de Janeiro     Gymnastics
4  2016  Summer  Rio de Janeiro     Gymnastics

                                     event medal
0  Weightlifting Women's Super-Heavyweight   NaN
1   Gymnastics Men's Individual All-Around   NaN
2          Gymnastics Men's Floor Exercise   NaN
3           Gymnastics Men's Parallel Bars   NaN
4          Gymnastics Men's Horizontal Bar   NaN

(271116, 15)

In [147]:
#cleaning steps
df_olympics_cleaning = olympics_df_uncleaned.dropna(subset=['medal'])
df_olympics_cleaning

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
8,62,Giovanni Abagnale,M,21.0,198.0,90.0,Italy,ITA,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Men's Coxless Pairs,Bronze
9,65,Patimat Abakarova,F,21.0,165.0,49.0,Azerbaijan,AZE,2016 Summer,2016,Summer,Rio de Janeiro,Taekwondo,Taekwondo Women's Flyweight,Bronze
10,73,Luc Abalo,M,31.0,182.0,86.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver
33,250,Saeid Morad Abdevali,M,26.0,170.0,80.0,Iran,IRI,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Middleweight, Greco-Roman",Bronze
58,455,Denis Mikhaylovich Ablyazin,M,24.0,161.0,62.0,Russia,RUS,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Team All-Around,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271104,129377,Hermann Otto Ludwig Weingrtner,M,31.0,NaN,NaN,Germany,GER,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Pommelled Horse,Silver
271109,131985,Thomas Xenakis,M,21.0,NaN,NaN,Greece,GRE,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Rope Climbing,Silver
271112,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Horse Vault,Silver
271113,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Parallel Bars,Silver
271115,135481,"Jules Alexis ""Louis"" Zutter",M,30.0,NaN,NaN,Switzerland,SUI,1896 Summer,1896,Summer,Athina,Gymnastics,Gymnastics Men's Pommelled Horse,Gold

In [149]:
# Define a mapping of Olympic host cities to their respective countries
city_to_country = {
    "Albertville": "France",
    "Amsterdam": "Netherlands",
    "Antwerp": "Belgium",
    "Antwerpen": "Belgium",  # Alternative spelling
    "Athens": "Greece",
    "Athina": "Greece",  # Alternative spelling
    "Atlanta": "USA",
    "Barcelona": "Spain",
    "Beijing": "China",
    "Berlin": "Germany",
    "Calgary": "Canada",
    "Chamonix": "France",
    "Cortina d'Ampezzo": "Italy",
    "Garmisch-Partenkirchen": "Germany",
    "Grenoble": "France",
    "Helsinki": "Finland",
    "Innsbruck": "Austria",
    "Lake Placid": "USA",
    "Lillehammer": "Norway",
    "London": "UK",
    "Los Angeles": "USA",
    "Melbourne": "Australia",
    "Mexico City": "Mexico",
    "Montreal": "Canada",
    "Moscow": "Russia",
    "Moskva": "Russia",  # Alternative spelling
    "Munich": "Germany",
    "Nagano": "Japan",
    "Oslo": "Norway",
    "Paris": "France",
    "Rio de Janeiro": "Brazil",
    "Rome": "Italy",
    "Roma": "Italy",  # Alternative spelling
    "Salt Lake City": "USA",
    "Sankt Moritz": "Switzerland",  # Alternative spelling of St. Moritz
    "Sapporo": "Japan",
    "Sarajevo": "Bosnia and Herzegovina",
    "Seoul": "South Korea",
    "Sochi": "Russia",
    "Squaw Valley": "USA",
    "St. Louis": "USA",
    "Stockholm": "Sweden",
    "Sydney": "Australia",
    "Tokyo": "Japan",
    "Torino": "Italy",
    "Vancouver": "Canada"
}


# Map the city column to the corresponding country
df_olympics_cleaning["host country"] = df_olympics_cleaning["city"].map(city_to_country)

# Show the first few rows with the new country column
print(df_olympics_cleaning.head())

     id                         name sex   age  height  weight        team  \
8    62            Giovanni Abagnale   M  21.0   198.0    90.0       Italy
9    65            Patimat Abakarova   F  21.0   165.0    49.0  Azerbaijan
10   73                    Luc Abalo   M  31.0   182.0    86.0      France
33  250         Saeid Morad Abdevali   M  26.0   170.0    80.0        Iran
58  455  Denis Mikhaylovich Ablyazin   M  24.0   161.0    62.0      Russia

    noc        games  year  season            city       sport  \
8   ITA  2016 Summer  2016  Summer  Rio de Janeiro      Rowing
9   AZE  2016 Summer  2016  Summer  Rio de Janeiro   Taekwondo
10  FRA  2016 Summer  2016  Summer  Rio de Janeiro    Handball
33  IRI  2016 Summer  2016  Summer  Rio de Janeiro   Wrestling
58  RUS  2016 Summer  2016  Summer  Rio de Janeiro  Gymnastics

                                        event   medal host country
8                  Rowing Men's Coxless Pairs  Bronze       Brazil
9                 Taekwondo Women's Flyweight  Bronze       Brazil
10                    Handball Men's Handball  Silver       Brazil
33  Wrestling Men's Middleweight, Greco-Roman  Bronze       Brazil
58           Gymnastics Men's Team All-Around  Silver       Brazil

/var/folders/7s/f7yn4z751wvb1kfzk28tvmf40000gn/T/ipykernel_87935/964391261.py:53: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [151]:
#drop duplicates 
num_duplicate_rows = df_olympics_cleaning.duplicated().sum()
print("Number of duplicate rows:", num_duplicate_rows)
df_olympics_cleaning = df_olympics_cleaning.drop_duplicates()

Number of duplicate rows: 11

In [153]:
# print number of duplicate rows after cleaning 
num_duplicate_rows = df_olympics_cleaning.duplicated().sum()
print("Number of duplicate rows after cleaning:", num_duplicate_rows)
# and isolate data from years 1960 to 2020 
df_olympics_cleaned_1960_2020 = df_olympics_cleaning[(df_olympics_cleaning['year'] >= 1960) & (df_olympics_cleaning['year'] <= 2020)]
df_olympics_cleaned_1960_2020

Number of duplicate rows after cleaning: 0

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal,host country
8,62,Giovanni Abagnale,M,21.0,198.0,90.0,Italy,ITA,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Men's Coxless Pairs,Bronze,Brazil
9,65,Patimat Abakarova,F,21.0,165.0,49.0,Azerbaijan,AZE,2016 Summer,2016,Summer,Rio de Janeiro,Taekwondo,Taekwondo Women's Flyweight,Bronze,Brazil
10,73,Luc Abalo,M,31.0,182.0,86.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver,Brazil
33,250,Saeid Morad Abdevali,M,26.0,170.0,80.0,Iran,IRI,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Middleweight, Greco-Roman",Bronze,Brazil
58,455,Denis Mikhaylovich Ablyazin,M,24.0,161.0,62.0,Russia,RUS,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Team All-Around,Silver,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209043,135042,Kazimierz Franciszek Zimny,M,25.0,172.0,60.0,Poland,POL,1960 Summer,1960,Summer,Roma,Athletics,"Athletics Men's 5,000 metres",Bronze,Italy
209058,135313,Gyula Zsivtzky,M,23.0,190.0,102.0,Hungary,HUN,1960 Summer,1960,Summer,Roma,Athletics,Athletics Men's Hammer Throw,Silver,Italy
209060,135327,Ryszard Zub,M,26.0,174.0,75.0,Poland,POL,1960 Summer,1960,Summer,Roma,Fencing,"Fencing Men's Sabre, Team",Silver,Italy
209061,135345,Viktor Alekseyevich Zubkov,M,23.0,202.0,88.0,Soviet Union,URS,1960 Summer,1960,Summer,Roma,Basketball,Basketball Men's Basketball,Silver,Italy
209063,135372,Giovanni Zucchi,M,29.0,185.0,92.0,Italy,ITA,1960 Summer,1960,Summer,Roma,Rowing,Rowing Men's Coxed Fours,Bronze,Italy

In [19]:
file_path = '/Users/samimorris/Desktop/UNI/SEM 8/COMP4010/Project 1/Part 3/olympics_cleaned.csv'
olympics_df = pd.read_csv(file_path)
print(olympics_df.head())
olympics_df.shape

    id                         name sex   age  height  weight        team  \
0   62            Giovanni Abagnale   M  21.0   198.0    90.0       Italy
1   65            Patimat Abakarova   F  21.0   165.0    49.0  Azerbaijan
2   73                    Luc Abalo   M  31.0   182.0    86.0      France
3  250         Saeid Morad Abdevali   M  26.0   170.0    80.0        Iran
4  455  Denis Mikhaylovich Ablyazin   M  24.0   161.0    62.0      Russia

   noc        games  year  season            city       sport  \
0  ITA  2016 Summer  2016  Summer  Rio de Janeiro      Rowing
1  AZE  2016 Summer  2016  Summer  Rio de Janeiro   Taekwondo
2  FRA  2016 Summer  2016  Summer  Rio de Janeiro    Handball
3  IRI  2016 Summer  2016  Summer  Rio de Janeiro   Wrestling
4  RUS  2016 Summer  2016  Summer  Rio de Janeiro  Gymnastics

                                       event   medal country
0                 Rowing Men's Coxless Pairs  Bronze  Brazil
1                Taekwondo Women's Flyweight  Bronze  Brazil
2                    Handball Men's Handball  Silver  Brazil
3  Wrestling Men's Middleweight, Greco-Roman  Bronze  Brazil
4           Gymnastics Men's Team All-Around  Silver  Brazil

(39783, 16)

In [29]:
#select relevant years and columns for analysis
olympics_df_ = olympics_df[(olympics_df["year"] >= 1960) & (olympics_df["year"] <= 2020)]
olympics_df_q1 = olympics_df_[['name', 'sex', 'height', 'weight', 'team', 'medal', 'year', 'city', 'games', 'country']]

#print the columns and a sample of the data
print(olympics_df_q1.columns)
olympics_df_q1

Index(['name', 'sex', 'height', 'weight', 'team', 'medal', 'year', 'city',
       'games', 'country'],
      dtype='object')

,name,sex,height,weight,team,medal,year,city,games,country
0,Giovanni Abagnale,M,198.0,90.0,Italy,Bronze,2016,Rio de Janeiro,2016 Summer,Brazil
1,Patimat Abakarova,F,165.0,49.0,Azerbaijan,Bronze,2016,Rio de Janeiro,2016 Summer,Brazil
2,Luc Abalo,M,182.0,86.0,France,Silver,2016,Rio de Janeiro,2016 Summer,Brazil
3,Saeid Morad Abdevali,M,170.0,80.0,Iran,Bronze,2016,Rio de Janeiro,2016 Summer,Brazil
4,Denis Mikhaylovich Ablyazin,M,161.0,62.0,Russia,Silver,2016,Rio de Janeiro,2016 Summer,Brazil
...,...,...,...,...,...,...,...,...,...,...
28395,Kazimierz Franciszek Zimny,M,172.0,60.0,Poland,Bronze,1960,Roma,1960 Summer,Italy
28396,Gyula Zsivtzky,M,190.0,102.0,Hungary,Silver,1960,Roma,1960 Summer,Italy
28397,Ryszard Zub,M,174.0,75.0,Poland,Silver,1960,Roma,1960 Summer,Italy
28398,Viktor Alekseyevich Zubkov,M,202.0,88.0,Soviet Union,Silver,1960,Roma,1960 Summer,Italy
28399,Giovanni Zucchi,M,185.0,92.0,Italy,Bronze,1960,Roma,1960 Summer,Italy

In [33]:
#check team names for cleaning
olympics_df_q1["team"].unique()

array(['Italy', 'Azerbaijan', 'France', 'Iran', 'Russia', 'Australia',
       'Spain', 'Jordan', 'Netherlands', 'Great Britain', 'United States',
       'New Zealand', 'South Africa', 'Indonesia', 'Germany',
       'Indonesia-1', 'Nigeria', 'Canada', 'Turkey', 'Uzbekistan',
       'Individual Olympic Athletes', 'Armenia', 'Serbia', 'Niger',
       'Brazil-1', 'Jamaica', 'Norway', 'Cuba', 'Colombia', 'Tunisia',
       'South Korea', 'Denmark', 'Sweden', 'Japan', 'Brazil', 'Malaysia',
       'Ethiopia', 'Switzerland', 'Kazakhstan', 'Qatar', 'Ukraine',
       'Slovakia', 'Romania', 'Croatia', 'Belgium', 'Hungary', 'Georgia',
       'Netherlands-1', 'Bahamas', 'Argentina', 'China', 'Kenya',
       'North Korea', 'Poland', "Cote d'Ivoire", 'Fiji', 'Bulgaria',
       'Philippines', 'Lithuania', 'Mongolia', 'Czech Republic',
       'Estonia', 'Mexico', 'Venezuela', 'Austria', 'China-1', 'Belarus',
       'Israel', 'Greece', 'Thailand', 'Vietnam', 'Chinese Taipei',
       'Egypt', 'Grenada', 'Bahrain', 'South Korea-1', 'United States-2',
       'Slovenia', 'Kosovo', 'Spain-2', 'Germany-1', 'Italy-1',
       'Russia-2', 'Algeria', 'India', 'Portugal', 'Ireland',
       'Tajikistan', 'Burundi', 'Dominican Republic', 'Finland',
       'Puerto Rico', 'Morocco', 'United States-1', 'Czech Republic-1',
       'Singapore', 'United Arab Emirates', 'Trinidad and Tobago',
       'Switzerland-1', 'Latvia-1', 'Latvia', 'Canada-1', 'Russia-1',
       'Austria-1', 'Kuwait', 'Saudi Arabia', 'Botswana',
       'Great Britain-1', 'Montenegro', 'Guatemala', 'France-2',
       'Moldova', 'Great Britain-2', 'Japan-1', 'Uganda', 'Cyprus',
       'Hong Kong', 'France-1', 'China-2', 'Denmark-1', 'Afghanistan',
       'Gabon', 'Germany-2', 'Canada-2', 'Iceland', 'Sweden-2',
       'Kyrgyzstan', 'Togo', 'Elvis Va', 'Zimbabwe', 'Brazil-2', 'Chile',
       'Don Schufro', 'Sudan', 'Clearwater', 'Mauritius', 'Bonaparte',
       'Cameroon', 'Spain-1', 'Nadine', 'Ecuador', 'Panama', 'Sunrise',
       'Salinero', 'Satchmo', 'Digby', 'Ukraine-1', 'China-3', 'Syria',
       'Paraguay', 'Serbia and Montenegro', 'Denmark-2', 'South Korea-2',
       'Switzerland-2', 'Hong Kong-2', 'Eritrea', 'Australia-1',
       'Macedonia', 'Sri Lanka', 'Poland-1', 'Mozambique', 'Costa Rica',
       'Barbados', 'Uruguay', 'Malaysia-1', 'Namibia', 'Zambia', 'Tonga',
       'Italy-2', 'Unified Team', 'Ghana', 'Pakistan', 'Czechoslovakia',
       'Unified Team-2', 'Unified Team-1', 'Peru', 'Luxembourg',
       'North Korea-1', 'Suriname', 'Czechoslovakia-1', 'Malaysia-2',
       'Soviet Union', 'East Germany', 'Yugoslavia', 'West Germany',
       'East Germany-2', 'Soviet Union-1', 'Netherlands Antilles',
       'Senegal', 'Liechtenstein', 'East Germany-1',
       'United States Virgin Islands', 'Soviet Union-2', 'Djibouti',
       'West Germany-1', 'Guyana', 'Tanzania', 'Lebanon', 'Bermuda',
       'West Germany-2', 'Romania-1', 'Mutafo', 'Bingo', 'Widgeon',
       'White Lady', 'Gem', 'Aphrodite', 'Rush VII', 'Lady C',
       'Barrenjoey', 'Pandora', 'Humbug V', 'Austria-2', 'Glider', 'Iraq',
       'Sirene', 'Web II', 'Tango', 'Venilia', 'Ballerina IV',
       'United Arab Republic', 'Nirefs', 'Skum', 'West Indies Federation',
       'Shrew II', 'Minotaur', 'Macky VI', 'Tornado', "Ma'Lindo"],
      dtype=object)

In [155]:
#clean the team names (e.g. United States, United States-1 and United States-2) and remove data for fake teams eg Shrek 
import re

def clean_team_name(team):
    # Remove numeric suffixes like '-1', '-2', etc.
    team = re.sub(r"-\d+$", "", team)
    return team

# Apply the cleaning function
olympics_df_q1["team"] = olympics_df_q1["team"].astype(str).apply(clean_team_name)

# Remove non-country entries (manually identified)
invalid_entries = [
    "Elvis Va", "Bonaparte", "Nadine", "Sunrise", "Salinero", "Satchmo", 
    "Digby", "Clearwater", "Don Schufro", "Mutafo", "Bingo", "Widgeon", 
    "White Lady", "Gem", "Aphrodite", "Rush VII", "Lady C", "Barrenjoey", 
    "Pandora", "Humbug V", "Glider", "Sirene", "Web II", "Tango", "Venilia", 
    "Ballerina IV", "Nirefs", "Skum", "Shrew II", "Minotaur", "Macky VI", 
    "Tornado", "Ma'Lindo"
]

# Keep only valid country names
olympics_df_q1 = olympics_df_q1[~olympics_df_q1["team"].isin(invalid_entries)]

# Check cleaned country names
print(olympics_df_q1["team"].unique())

['Italy' 'Azerbaijan' 'France' 'Iran' 'Russia' 'Australia' 'Spain'
 'Jordan' 'Netherlands' 'Great Britain' 'United States' 'New Zealand'
 'South Africa' 'Indonesia' 'Germany' 'Nigeria' 'Canada' 'Turkey'
 'Uzbekistan' 'Individual Olympic Athletes' 'Armenia' 'Serbia' 'Niger'
 'Brazil' 'Norway' 'Cuba' 'Colombia' 'Tunisia' 'South Korea' 'Denmark'
 'Sweden' 'Japan' 'Jamaica' 'Malaysia' 'Ethiopia' 'Switzerland'
 'Kazakhstan' 'Qatar' 'Ukraine' 'Slovakia' 'Romania' 'Croatia' 'Belgium'
 'Hungary' 'Georgia' 'Bahamas' 'Argentina' 'China' 'Kenya' 'North Korea'
 'Poland' "Cote d'Ivoire" 'Fiji' 'Bulgaria' 'Philippines' 'Lithuania'
 'Mongolia' 'Czech Republic' 'Estonia' 'Mexico' 'Venezuela' 'Austria'
 'Belarus' 'Israel' 'Greece' 'Thailand' 'Vietnam' 'Chinese Taipei' 'Egypt'
 'Grenada' 'Bahrain' 'Slovenia' 'Kosovo' 'Algeria' 'India' 'Portugal'
 'Ireland' 'Tajikistan' 'Burundi' 'Dominican Republic' 'Finland'
 'Puerto Rico' 'Morocco' 'Singapore' 'United Arab Emirates'
 'Trinidad and Tobago' 'Latvia' 'Kuwait' 'Saudi Arabia' 'Botswana'
 'Montenegro' 'Guatemala' 'Moldova' 'Uganda' 'Cyprus' 'Hong Kong'
 'Afghanistan' 'Gabon' 'Iceland' 'Kyrgyzstan' 'Togo' 'Zimbabwe' 'Chile'
 'Sudan' 'Mauritius' 'Cameroon' 'Ecuador' 'Panama' 'Syria' 'Paraguay'
 'Serbia and Montenegro' 'Eritrea' 'Macedonia' 'Sri Lanka' 'Mozambique'
 'Costa Rica' 'Barbados' 'Uruguay' 'Namibia' 'Zambia' 'Tonga'
 'Unified Team' 'Ghana' 'Pakistan' 'Czechoslovakia' 'Peru' 'Luxembourg'
 'Suriname' 'Soviet Union' 'East Germany' 'Yugoslavia' 'West Germany'
 'Senegal' 'Liechtenstein' 'United States Virgin Islands' 'Djibouti'
 'Guyana' 'Tanzania' 'Lebanon' 'Bermuda' 'Iraq' 'West Indies Federation']

In [159]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
from dash import dash_table
import plotly.express as px
import pandas as pd

#data selection
olympics_df_q1 = pd.read_csv("olympics_data.csv")
olympics_df_q1["medal"] = olympics_df_q1["medal"].astype(str)
olympics_df_q1 = olympics_df_q1.dropna(subset=["medal", "team", "year"])

# initialize app + create layout
app = dash.Dash(__name__)
app.layout = html.Div([
    html.H1("Olympics Data Dashboard"),

    dcc.Dropdown(
        id='country-dropdown',
        options=[{'label': country, 'value': country} for country in olympics_df_q1["team"].unique()],
        multi=True,
        placeholder="Select countries..."
    ),

    dcc.Dropdown(
        id='sort-order-dropdown',
        options=[
            {'label': 'Ascending', 'value': 'asc'},
            {'label': 'Descending', 'value': 'desc'}
        ],
        value='desc',
        clearable=False
    ),

    # Graph1: amount of medals per selected country
    dcc.Graph(id='medal-bar-chart'),

    # Graph2: medals for selected country per game
    html.H2("Medals Over Time"),
    dcc.Graph(id='medal-line-chart'),

    # Graph3: top 10 Athletes in selected country in selected game
    html.H3("Top 10 Athletes and Their Medals"),
    dcc.Graph(id='athlete-bar-chart'),
    
    #Table1: for selected country and Olympic, show each athlete that achieved medals and what medal they achieved in a table
    html.H3("All Athletes and Medals for Selected Country and Olympics"),
    dash_table.DataTable(
        id='athlete-table',
        columns=[
            {'name': 'Athlete', 'id': 'name'},
            {'name': 'Gold', 'id': 'Gold'},
            {'name': 'Silver', 'id': 'Silver'},
            {'name': 'Bronze', 'id': 'Bronze'},
            {'name': 'Total Medals', 'id': 'total'}
        ],
        style_table={'overflowX': 'auto'},
        style_cell={'textAlign': 'left', 'padding': '5px'},
        style_header={'backgroundColor': '#f9f9f9', 'fontWeight': 'bold'},
        style_data_conditional=[
            {
                'if': {'column_id': 'Gold'},
                'backgroundColor': '#FFF8DC'
            },
            {
                'if': {'column_id': 'Silver'},
                'backgroundColor': '#F5F5F5'
            },
            {
                'if': {'column_id': 'Bronze'},
                'backgroundColor': '#FAEBD7'
            },
        ]
    )
])

# Callback 1:  bar chart for selected countries
@app.callback(
    Output('medal-bar-chart', 'figure'),
    [Input('country-dropdown', 'value'),
     Input('sort-order-dropdown', 'value')]
)
def update_country_graph(selected_countries, sort_order):
    if not selected_countries:
        return px.bar(title="Select at least one country to display medal counts")

    filtered_df = olympics_df_q1[olympics_df_q1["team"].isin(selected_countries)]

    medal_counts = (filtered_df.groupby(["team", "medal"]).size()
                    .reset_index(name="count"))
    #count total medals
    total_medals = medal_counts.groupby("team")["count"].sum().reset_index()
    total_medals = total_medals.sort_values(by="count", ascending=(sort_order == "asc"))

    #use total medal count to count gold, silver, bronze
    medal_counts = medal_counts.merge(total_medals[["team", "count"]], on="team", suffixes=("", "_total"))
    medal_counts = medal_counts.sort_values(by="count_total", ascending=(sort_order == "asc"))

    #make sure gold at top, silver in middle, bronze at bottom
    medal_order = ["Bronze", "Silver", "Gold"]
    medal_counts["medal"] = pd.Categorical(medal_counts["medal"], categories=medal_order, ordered=True)
    medal_counts = medal_counts.sort_values(by=["count_total", "medal"], ascending=[(sort_order == "asc"), True])

    #plot 
    fig = px.bar(
        medal_counts, x="team", y="count", color="medal", barmode="stack",
        title="Medal Counts by Country",
        labels={"count": "Number of Medals", "team": "Country", "medal": "Medal Type"},
        color_discrete_map={"Gold": "#FFD700", "Silver": "#C0C0C0", "Bronze": "#CD7F32"}
    )

    for team in total_medals["team"]:
        total = total_medals.loc[total_medals["team"] == team, "count"].values[0]
        fig.add_annotation(
            x=team, y=total, text=str(total), showarrow=False, font=dict(size=11, color="black")
        )

    #clickmode and graph size 
    fig.update_layout(height=700, clickmode="event+select")
    return fig

# Callback 2: Update line chart when clicking on a country's bar
@app.callback(
    Output('medal-line-chart', 'figure'),
    [Input('medal-bar-chart', 'clickData')]
)
def update_medal_trend(clickData):
    if clickData is None:
        return px.line(title="Click on a country's bar to see medal trends")

    #based on click data from graph 1 
    selected_country = clickData["points"][0]["x"]
    #find country medals for selected country from clickdata graph1
    country_medals = olympics_df_q1[olympics_df_q1["team"] == selected_country]
    medals_per_games = (country_medals.groupby(["games", "city", "country"]).size()
                        .reset_index(name="count").sort_values("games"))

    #make linegraph 
    fig = px.line(
        medals_per_games, x="games", y="count", markers=True,
        title=f"Total Medals Won by {selected_country} Over Different Olympics",
        labels={"count": "Number of Medals", "games": "Olympic Games Edition", "country": "Host Country"},
        hover_data={"city": True, "country": True} 
    )

    #format graph
    fig.update_traces(line=dict(color="#800080", width=3))
    fig.update_layout(
        height=600, width=1200, clickmode="event+select",
        xaxis=dict(tickangle=-30, tickmode="array", tickfont=dict(size=10), title_standoff=10)
    )
    return fig

# Callback 3: update top 10 athletes bar chart and table
@app.callback(
    [Output('athlete-bar-chart', 'figure'),
     Output('athlete-table', 'data')],
    [Input('medal-bar-chart', 'clickData'),
     Input('medal-line-chart', 'clickData')]
)

#use click data from previous country selection and specific olympic game selection
def update_athlete_graph(clickData_country, clickData_game):
    if not clickData_country or not clickData_game:
        return px.bar(title="Click on a country's bar to see top athletes for a selected Olympic Game"), []

    selected_country = clickData_country["points"][0]["x"]
    selected_game = clickData_game["points"][0]["x"]

    filtered_athletes = olympics_df_q1[
        (olympics_df_q1["team"] == selected_country) &
        (olympics_df_q1["games"] == selected_game)
    ]
    #find athletes that achieved medals and count them
    filtered_athletes = filtered_athletes[filtered_athletes["medal"].isin(["Gold", "Silver", "Bronze"])]
    all_athlete_counts = filtered_athletes.groupby(["name", "medal"]).size().reset_index(name="count")

    #create table with those results
    pivot_table = all_athlete_counts.pivot(index="name", columns="medal", values="count").fillna(0).astype(int)
    pivot_table = pivot_table.reindex(columns=["Gold", "Silver", "Bronze"], fill_value=0)
    pivot_table["total"] = pivot_table.sum(axis=1)
    pivot_table = pivot_table.sort_values(by=["total", "Gold", "Silver", "Bronze"], ascending=[False, False, False, False]).reset_index()

    table_data = pivot_table.to_dict("records")

    top_10_names = pivot_table.head(10)["name"]
    top_athletes = all_athlete_counts[all_athlete_counts["name"].isin(top_10_names)]

    top_athletes_total = top_athletes.groupby("name")["count"].sum().reset_index(name="total_count")
    top_athletes = top_athletes.merge(top_athletes_total, on="name")

    top_athletes["medal"] = pd.Categorical(top_athletes["medal"], categories=["Gold", "Silver", "Bronze"], ordered=True)
    top_athletes = top_athletes.sort_values(by=["total_count", "medal"], ascending=[False, True])

    fig = px.bar(
        top_athletes,
        x="name",
        y="count",
        color="medal",
        barmode="stack",
        title=f"Top 10 Athletes from {selected_country} in {selected_game} (Total Medals: {len(filtered_athletes)})",
        labels={"count": "Number of Medals", "name": "Athlete", "medal": "Medal Type"},
        color_discrete_map={"Gold": "#FFD700", "Silver": "#C0C0C0", "Bronze": "#CD7F32"}
    )

    fig.update_layout(
        xaxis_title="Athlete",
        yaxis_title="Number of Medals",
        xaxis_tickangle=30,
        barmode="stack",
        coloraxis_showscale=False
    )

    return fig, table_data

# Run the app
if __name__ == '__main__':
    app.run(debug=True, port=7001)